import dataclasses
from collections.abc import Sequence
from typing import Any, Type

def get_cached_type_hints(clazz: Type[Any]) -> dict[str, Type[Any]]: ...
def get_cached_fields(clazz: Type[Any]) -> tuple[dataclasses.Field, ...]: ...
def get_cached_class_args(
    field_type: Type[Any],
) -> tuple[Type[Any], Sequence[Type[Any]]]: ...
