import dataclasses

from .handler import Clazz, ClazzArgs

def get_cached_type_hints(clazz: Clazz) -> dict[str, Clazz]: ...
def get_cached_fields(clazz: Clazz) -> tuple[dataclasses.Field, ...]: ...
def examine_class(field_type: Clazz) -> tuple[Clazz, ClazzArgs]: ...
